### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by mde-dfakto-com** [Kaporos/JiraOdooTimesheetLink#1]
Hello,

I was wondering if it would be possible for you to add a License to your project specifying terms
of use of the code. Without a license we may assume no rights are granted to us.

We would be interested in using this at dFakto, so of course, any open-soure & free usage License
like the GPL family (gpl, agpl, lgpl): (https://choosealicense.com/licenses/gpl-3.0/)
or the less constraining Mozilla License (https://choosealicense.com/licenses/mpl-2.0/) would be ideal for us.

In any case, thanks for your work.

**Comment by tdaron** [comment]
Done :)
