### ISSUE TITLE
Logged work in the past is logged today

### ISSUE THREAD

**Issue by jem-dfakto-com** [Kaporos/JiraOdooTimesheetLink#2]
Hi,
I've logged some time (30min) in JIRA in the past (on Thursday) but in Odoo the time is logged for today (Friday). The time in Odoo should match the date defined on JIRA
![2](https://user-images.githubusercontent.com/78603171/107042919-92414700-67c2-11eb-8c46-b234bbd07aa5.jpg)
![1](https://user-images.githubusercontent.com/78603171/107042920-92d9dd80-67c2-11eb-9c12-c17c8bca18cb.jpg)

**Comment by tdaron** [comment]
Hi!

It should be fixed :) But I can't check by myself, could you test it and send feedbacks to me?

Thanks!

**Comment by jem-dfakto-com** [comment]
Hi Theo ! 
I did test again and it works great thanks :)
