### ISSUE TITLE
Avoid trying to create timesheet in Odoo if the code in jira is empty

### ISSUE THREAD

**Issue by pierresebastien** [Kaporos/JiraOdooTimesheetLink#3]
For the moment, for each work log created in jira, we try to create a timesheet record in Odoo even if the code is empty in jira issue. We should add a condition around here : https://github.com/Kaporos/JiraOdooTimesheetLink/blob/6e548046af482e2bf9b8ae78fadebb9c82ba5cf0/main.go#L62 to test if the code is not empty (or in the sub function if you prefer)

**Comment by tdaron** [comment]
I'll try to do that this weekend!

Thanks for the issue :)

**Comment by tdaron** [comment]
Fixed :)
