### ISSUE TITLE
Avoid hardcoding jira custom field id in the code

### ISSUE THREAD

**Issue by pierresebastien** [Kaporos/JiraOdooTimesheetLink#4]
The timesheet code in jira is a custom field and custom fields have an id that will differ from one instance to another because it is related to the order of creation of custom fields. I think we should avoid hardcoding this id in the code and find a way to have it based on a variable (environment/config file, other) : https://github.com/Kaporos/JiraOdooTimesheetLink/blob/6e548046af482e2bf9b8ae78fadebb9c82ba5cf0/jira/json.go#L28

**Comment by tdaron** [comment]
Fixed !
